# File: .readthedocs.yaml

version: 2

# Build from the doc/ directory with Sphinx
sphinx:
  configuration: doc/source/conf.py

# Explicitly set the version of Python and its requirements
python:
  version: 3.8
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
