[build-system]
requires = [
    "setuptools>=36.6",
    "packaging<=21.3",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-Werror --strict-config --strict-markers"
testpaths = [
    "tests",
]
