name: Documentation on GPU

on:
  # Limit this workflow to pushes and PRs to particular branches (e.g. main or
  # release branches) so that the workflows don't run and automatically fail on
  # branches in forked repositories (where there is typically no `gpu` worker to
  # run on).
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    # The slightly odd shell call is to force bash to read .bashrc, which is
    # necessary for having conda behave sensibly.
    shell: bash -l {0}

jobs:
  build:
    name: Build HTML documentation
    runs-on: [self-hosted, gpu]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        env:
          CONDA: /home/runnerx/miniconda3
        with:
          auto-update-conda: true
          python-version: "3.9"
          miniconda-version: "latest"

      - name: Install documentation dependencies
        run: |
          python -mpip install -r doc/requirements.txt

      - name: Install QuTiP from GitHub
        # temporally pinning qutip version
        # should be restored to dev.major
        run: |
          python -mpip install git+https://github.com/qutip/qutip.git@c6d68c04a02c4fbeed14e0e07d44ab6021d53c8d 
          python -c 'import qutip; qutip.about()'

      - name: Install qutip-cupy from GitHub
        run: |
          conda install -c conda-forge cupy
          python -mpip install .[full]
          python -c 'import qutip_cupy; print(qutip_cupy.__version__)'

      - name: Build documentation
        working-directory: doc
        run: |
          make html

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: qutip-cupy_html_docs
          path: doc/_build/html/*
          if-no-files-found: error
